name: CI

on:
  pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    name: Test changed-files
    steps:
      # Checkout the source code
      - name: 'Checkout source code'
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Check for changes
        id: checkForChanges
        run: |
          git fetch origin master
          TS_NOCHECK_GREP_RESULTS=$(git diff origin/master..HEAD | grep '@ts-nocheck')
          cat "$TS_NOCHECK_GREP_RESULTS"
          COUNT=$(echo "$TS_NOCHECK_GREP_RESULTS" | grep -c '^+')
          if [ "$COUNT" -gt 0 ]; then echo "Found non-zero '@ts-nocheck' lines! :("; exit 1; else echo 'Good to go! :)'; fi

