name: CI

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    name: Test changed-files
    steps:
      - name: Check for changes
        id: checkForChanges
        run: |
          git fetch origin master
          git diff origin/master..HEAD > PR_DIFF
          cat PR_DIFF | grep '@ts-nocheck' > NO_CHECK_GREP_RESULTS
          cat NO_CHECK_GREP_RESULTS
          cat NO_CHECK_GREP_RESULTS | grep -c '^+' && exit 1 || echo 'Awesome!'
