name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    name: Test changed-files
    steps:
      # Checkout the source code
      - name: 'Checkout source code'
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # Check for changes
      - name: Check for changes
        id: checkForChanges
        run: |
          git diff ${{ github.event.before }} ${{ github.sha }} | grep '@ts-nocheck' | grep -c '^+' && echo 'Booo!' >&2 || echo 'Awesome!'
